"""
Numen CLI — start the math solver server with a single command.

Usage:
    numen up                    # start on http://localhost:7860
    numen up --port 8080        # custom port
    numen up --share            # public Gradio share link
    numen server                # alias for 'numen up'
    numen version               # print version and exit
"""

import argparse
import sys


VERSION = "1.0.0"

BANNER = r"""
  _   _
 | \ | |_   _ _ __ ___   ___ _ __
 |  \| | | | | '_ ` _ \ / _ \ '_ \
 | |\  | |_| | | | | | |  __/ | | |
 |_| \_|\__,_|_| |_| |_|\___|_| |_|

  Math Solver for Everyone  v{version}
  100% accurate · Free · Open source
""".format(version=VERSION)


def cmd_up(args):
    """Start the Numen web server."""
    print(BANNER)
    print(f"  Starting Numen on port {args.port}...")
    if args.share:
        print("  Public share link will be generated by Gradio.")
    print(f"  Local URL: http://localhost:{args.port}")
    print("  Press Ctrl+C to stop.\n")

    from numen.app import create_public_ui
    import gradio as gr

    app = create_public_ui()

    launch_kwargs = dict(
        server_name=args.host,
        server_port=args.port,
        share=args.share,
        show_error=True,
        quiet=False,
    )
    # Gradio 6 moved theme to launch(); try both ways for compatibility
    try:
        app.launch(**launch_kwargs, theme=gr.themes.Soft())
    except TypeError:
        app.launch(**launch_kwargs)


def cmd_version(_args):
    print(f"Numen {VERSION}")


def main():
    parser = argparse.ArgumentParser(
        prog="numen",
        description="Numen — Math Solver for Everyone",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Examples:\n"
            "  numen up                  Start on http://localhost:7860\n"
            "  numen up --port 8080      Use a different port\n"
            "  numen up --share          Generate a public Gradio link\n"
            "  numen server              Alias for 'numen up'\n"
            "  numen version             Print version\n"
        ),
    )

    sub = parser.add_subparsers(dest="command", metavar="COMMAND")

    # ── numen up / numen server ──────────────────────────────────────────
    def add_server_args(p):
        p.add_argument(
            "--port", "-p",
            type=int,
            default=7860,
            help="Port to listen on (default: 7860)",
        )
        p.add_argument(
            "--host",
            default="0.0.0.0",
            help="Host to bind to (default: 0.0.0.0)",
        )
        p.add_argument(
            "--share",
            action="store_true",
            help="Create a public Gradio share link",
        )
        p.set_defaults(func=cmd_up)

    add_server_args(sub.add_parser("up",     help="Start the Numen web server"))
    add_server_args(sub.add_parser("server", help="Alias for 'numen up'"))

    # ── numen version ────────────────────────────────────────────────────
    ver_p = sub.add_parser("version", help="Print version and exit")
    ver_p.set_defaults(func=cmd_version)

    # Default: no subcommand → same as 'numen up'
    args = parser.parse_args()

    if not args.command:
        # Running bare `numen` — show help
        parser.print_help()
        sys.exit(0)

    args.func(args)


if __name__ == "__main__":
    main()
